name: Create and upload a new release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create a new release on github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # provided by github actions, no need to configure
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Summary:
              - TODO
  deploy:
    name: Deploy a new release to Pypi
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine

      - name: Build packages
        run: python setup.py sdist

      - name: Upload packages
        run: python -m twine upload dist/*
        env: 
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
