name: Run tests, deploy tagged releases

on:
  push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.7", "pypy-3.8", "pypy-3.9"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install -r test_requirements.txt

      - name: Run unittests
        run: python -m pytest

      - name: Verify dependencies
        run: python -m safety check

      - name: Verify code style
        run: python -m flake8 -v

      - name: Verify code typing
        # Installation of typed-ast on pypy-3.7 is broken
        # We re-install mypy here for the other pypy's which don't get mypy from requirements file.
        if: ${{ matrix.python_version != 'pypy-3.7' }}
        run: |
          python -m pip install mypy
          python -m mypy --config mypy.ini mollie/

  deployment:
    name: Deploy a new release to Pypi
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}  # only on tagged commits
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install --upgrade build twine

      - name: Build packages
        run: python -m build

      - name: Upload packages
        run: python -m twine upload dist/*
        env: 
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

  release:
    name: Create a new release on github
    needs: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # provided by github actions, no need to configure
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          body: |
            Summary:
              - TODO
