name: Run tests

on:
  push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install -r test_requirements.txt

      - name: Run unittests
        run: python -m pytest

      - name: Verify dependencies
        run: safety check

